Tournament description
ChampionTrackers/CTracker pull request #16
Opened 2024-05-08 17:25 UTC by Gabstxr

2024-05-09 00:39 UTC, GabrielleCGNeves requested changes
muito bom, só ajustar alguns detalhes

2024-05-09 00:39 UTC, GabrielleCGNeves commented on lib/view/view_tournament_description.dart
> +class MyApp extends StatelessWidget {
Trocar o nome da classe de "MyApp" para "ViewTournament"

2024-05-09 00:39 UTC, GabrielleCGNeves commented on lib/view/view_tournament_description.dart
> +}
Tirar a função "main" já que a página será só uma view

2024-05-09 00:39 UTC, GabrielleCGNeves commented on lib/view/view_tournament_description.dart
> +                  const SizedBox(height: 16), // Espaçamento entre a imagem e o Título
Rever as sizedboxes pois está tendo erros de overflow

2024-05-09 00:39 UTC, GabrielleCGNeves commented on lib/view/view_tournament_description.dart
> +    return Padding(
Adicionar um singlechildscroll view

2024-05-09 21:23 UTC, GabrielleCGNeves requested changes

2024-05-09 21:23 UTC, GabrielleCGNeves commented on lib/view/view_tournament_description.dart
> +        padding: const EdgeInsets.all(16),
ajustar padding geral

2024-05-09 21:23 UTC, GabrielleCGNeves commented on lib/view/view_tournament_description.dart
> +                  crossAxisAlignment: CrossAxisAlignment.start,
ajustar alinhamento do card de informações, deixar como "strech"

2024-05-09 21:23 UTC, GabrielleCGNeves commented on lib/view/view_tournament_description.dart
> +                    ),
fazer o alinhamento do texto ficar como no figma, talvez dê pra utilizar duas colunas. segundo o @ericksantos12 deve dar para usar o crossaxisalignment

2024-05-09 21:23 UTC, GabrielleCGNeves commented on lib/view/view_tournament_description.dart
> +                              ), // Espaço entre os Containers
pilantra copiando do nathan, são bem diferentes do que está no figma, alem disso tem que dar uma alinhada

2024-05-09 21:23 UTC, GabrielleCGNeves commented on lib/view/view_tournament_description.dart
> +                            'Sword Fighters', // Título abaixo das informações
ajustar alinhamento do título, deixar mais para a esquerda ou a imagem mais para direita, igual no figma

2024-05-09 21:23 UTC, GabrielleCGNeves commented on lib/view/view_tournament_description.dart
> +}
você não resolveu!! troca o MyApp para ViewTournament e tira a função main

2024-05-09 23:13 UTC, Gabstxr commented on lib/view/view_tournament_description.dart
> +}
agora fiz, perdoe minha lerdeza

2024-05-11 13:50 UTC, GabrielleCGNeves approved these changes
B 👍

2024-05-11 13:51 UTC, merged