💄 Layout feed
ChampionTrackers/CTracker pull request #17
Opened 2024-05-11 00:35 UTC by ericksantos12

Este PR cria a interface da tela Feed Pessoal, que contém uma lista de palpites realizados, lista das equipes e torneios favoritos.

Além da criação da interface, eu também tomei a liberdade de editar a versão do aplicativo no pubspec e rodar o comando `dart fix` para arrumar problemas de boas práticas e sintaxe que o dart identificar. 

A última música da minha playlist que ouvi quando terminei o código foi [Mass Destruction -Reload-](https://www.youtube.com/watch?v=Q6q6pDC6Mas)

2024-05-11 14:00 UTC, GabrielleCGNeves requested changes
não vê o prototipo né

2024-05-11 14:00 UTC, GabrielleCGNeves commented on lib/view/view_feed.dart
> +                        ),
ajustar tamanho da linha de acordo com o que pede no figma

2024-05-11 14:00 UTC, GabrielleCGNeves commented on lib/view/view_feed.dart
> +              color: AppColor.primaryColor,
ajustar opacidade da cor (se ficar ruim deixa como tá)

2024-05-11 14:00 UTC, GabrielleCGNeves commented on lib/view/view_feed.dart
> +      color: AppColor.primaryColor,
ajusta a cor

2024-05-11 14:01 UTC, ericksantos12 commented
> não vê o prototipo né

fizeram o protótipo errado tambem

2024-05-15 23:04 UTC, GabrielleCGNeves approved these changes
mb 👍

2024-05-15 23:04 UTC, merged